logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG


spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: SET_IN_RUN_PROPS
            client-secret: SET_IN_RUN_PROPS
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/photoslibrary.readonly  # read albums
              - https://www.googleapis.com/auth/photoslibrary.sharing   # share albums
              - https://www.googleapis.com/auth/photoslibrary.appendonly # create albums
              - https://www.googleapis.com/auth/plus.circles.read       # read Google+ circles
              - https://www.googleapis.com/auth/plus.me                 # read Google+ circles
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/gphoto_share
google:
  photos.api:
    host: photoslibrary.googleapis.com
    albums: /v1/albums
    sharedAlbums: /v1/sharedAlbums
  plus.api:
    host: www.googleapis.com
    circles: /plusDomains/v1/people/me/circles